### ISSUE TITLE
Add Hover Effect On "Get Started" Button & "Lern more about Ignite" Button

### ISSUE THREAD

**Issue by JrG-One** [charu1603/Ignyte-website#17]
@charu1603 Please assign me this issue I'm Contributor under SWOC 2024

Description:
Currently, the buttons lack a hover effect.

Proposed Solution:
Implement a hover effect for buttons that provides visual feedback to users when they hover over them.

Screenshots
![image](https://github.com/charu1603/Ignyte-website/assets/118374998/0fd33f24-340f-422e-b41a-2aa0fef3d33e)
![image](https://github.com/charu1603/Ignyte-website/assets/118374998/8b13c983-7208-46d3-b0b4-a26c36a6dd59)

**Comment by JrG-One** [comment]
@charu1603 Please add label as SWOC24

**Comment by JrG-One** [comment]
@charu1603 , Could you please tell me the command to run this project, as it was not stated in the README?

**Comment by charu1603** [comment]
To run this project, start with 'npm i' to install dependencies, and then use 'npm run dev' to launch it .

**Comment by Jainil2004** [comment]
hello @charu1603 I am Jainil, contributor in SWOC S4. If the issue is not yet resolved. Then I would love to work on the issue and provide you with a possible fix for it. 
Thank you
