### ISSUE TITLE
Bug in the navabr

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [charu1603/Ignyte-website#2]
On clicking on the about in the navbar, there's no response

**Comment by younikarn** [comment]
Can I take this issue? Please assign it to me.

**Comment by Muhammad-Owais-Warsi** [comment]
@younikarn Okay go ahead..

**Comment by charu1603** [comment]
Please be patient, guys. Starting on January 1st, I will assign the issues based on the priority of the person who asks first .

**Comment by Muhammad-Owais-Warsi** [comment]
Thanks for the information @charu1603

**Comment by Muhammad-Owais-Warsi** [comment]
Hey, @charu1603 I want some help, i tried solving the issue, but I don't have experience in GSAP you used their. Can you please guide me a little bit or provide me with some documentations links.

**Comment by rohits-web03** [comment]
#### @Muhammad-Owais-Warsi I think that GSAP knowledge is not needed to fix this particular bug.
#### If you still want to know more about GSAP, here's the [documention](https://gsap.com/docs/v3/)

**Comment by charu1603** [comment]
yes @rohits-web03 is right, it has nothing to do with the gsap.

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @charu1603 I completed the issue and raised the PR, can you please analyze and merge it..
