### ISSUE TITLE
Button on about us

### ISSUE THREAD

**Issue by nepalivai** [charu1603/Ignyte-website#35]
Here are a few issues with the button on About Us section
<img width="926" alt="image" src="https://github.com/charu1603/Ignyte-website/assets/108126089/6595f628-471d-4c39-ba06-08999ef0dbe5">
hover
<img width="271" alt="image" src="https://github.com/charu1603/Ignyte-website/assets/108126089/f5d02a2c-14db-44bc-aa91-afa750e032f8">

1. The button does not lead anywhere, just there for show.
2. Very small effect on hover almost unnoticeable 
3. too much data on the button just 'learn more' is enough.

**Comment by mxyznk** [comment]
Hi, pls assign this to me
