### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Niharika0104** [charu1603/Ignyte-website#5]
the text is the very bottom of the footer.We need to add bit of padding  around it.
<img width="953" alt="snap" src="https://github.com/charu1603/Ignyte-website/assets/124892559/60af8fb1-3825-4025-8aec-ad85ded472ca">

please assign this issue to me.
 I will fix it asap

**Comment by charu1603** [comment]
It's not a bug, @Niharika0104; rather, it aligns with a design requirement
